# Example NixOS machine configuration
# =============================================================================
# Copy this file and rename it to your hostname.nix (e.g., my-desktop.nix)
# Then add the machine to flake.nix under nixosConfigurations
# =============================================================================
{ config, pkgs, lib, ... }:

{
  # Import hardware configuration generated by nixos-generate-config
  # imports = [
  #   ./hardware-configuration.nix
  # ];

  # Bootloader configuration
  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;

  # Machine-specific packages
  # environment.systemPackages = with pkgs; [
  #   # Add machine-specific packages here
  # ];

  # Machine-specific services
  # services = {
  #   # Enable services specific to this machine
  # };

  # This assertion ensures the module is valid while keeping it minimal
  assertions = [
    {
      assertion = true;
      message = "machines/nixos/example.nix is a template file.";
    }
  ];
}
